version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ideacode-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=z$27^7tvmsJs
      - POSTGRES_DB=users
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ideacode-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - ./static:/app/static
    environment:
      - DB_HOST=postgres
      - DB_NAME=users
      - DB_USER=admin
      - DB_PASSWORD=z$27^7tvmsJs
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ideacode-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - ORIGIN=http://localhost:3000
      - API_URL=http://backend:8000 

volumes:
  postgres_data: 