version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ideacode-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./ideacode.db
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ideacode-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - ORIGIN=http://localhost:3000
      - API_URL=http://backend:8000
